### PR TITLE
Cleaned up project structure and updated deps

### PR DESCRIPTION
**Pull request by dosier**
- removed runtime plugin
- use allProjects block to define global proj settings
- updated dependencies

### CODE REVIEW

**Comment by ConnorDY** [comment]
Does this address #2?

**Review by ConnorDY — DISMISSED** [review]
Looks good.
Tested on my Linux machine with `./gradlew clean run` and everything worked as expected.

**Review by ScoreUnder — DISMISSED** [review]

**Comment by ScoreUnder** [comment]
Minor question, is the version numbering now based on API version?

**Comment by dosier** [comment]
> Minor question, is the version numbering now based on API version?

At the moment I made it so both modules share the same version. It would probably be better to  start numbering the versions separately.  When we actually distribute the API module as a standalone module (that others can use to create plugins) we should for sure start numbering them separately.

**Pull request merged**
